---
AWSTemplateFormatVersion: 2010-09-09
Description: DMS Trading Portal PTPCore

Parameters:
  Cluster:
    Type: String

  DesiredCount:
    Type: Number
    Default: 3

  LaunchType:
    Type: String
    Default: Fargate
    AllowedValues:
      - Fargate
      - EC2

  TargetGroup:
    Type: String

  SourceSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>


Conditions:
  Fargate: !Equals [ !Ref LaunchType, "Fargate" ]

  EC2: !Equals [ !Ref LaunchType, "EC2" ]


Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}

  FargateService:
    Type: AWS::ECS::Service
    Condition: Fargate
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref SourceSecurityGroup
          Subnets: !Ref Subnets
      LoadBalancers:
        - ContainerName: ptpcore
          ContainerPort: 8888
          TargetGroupArn: !Ref TargetGroup
      Tags:
       - Key: "Application"
         Value: "Programmatic Trading Portal"
       - Key: "CostCenter"
         Value: "55210"
       - Key: "Department"
         Value: "DSTV Media Sales"
       - Key: "Project"
         Value: "DMS Programmatic Trading Portal"
       - Key: "Environment"
         Value: "UAT"
       - Key: "Owner"
         Value: "Rani.Bisal"
       - Key: "Team"
         Value: "Business Optimization"
       - Key: "Vendor"
         Value: "Tata Elxsi"

  EC2Service:
    Type: AWS::ECS::Service
    Condition: EC2
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LaunchType: EC2
      LoadBalancers:
        - ContainerName: ptpcore
          ContainerPort: 8888
          TargetGroupArn: !Ref TargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}
      RequiresCompatibilities:
        - !If [ Fargate, "FARGATE", "EC2" ]
      Memory: 512
      Cpu: 256
      NetworkMode: !If [ Fargate, "awsvpc", "bridge" ]
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: ptpcore
          Image: 433415038121.dkr.ecr.eu-west-1.amazonaws.com/ptpcore
          
          Essential: true
          Memory: 256
          MountPoints:
            - SourceVolume: ptp-vol
              ContainerPath: /opt/ptp-vol
          PortMappings:
            - ContainerPort: 8888
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: !Ref AWS::StackName
      Tags:
       - Key: "Application"
         Value: "Programmatic Trading Portal"
       - Key: "CostCenter"
         Value: "55210"
       - Key: "Department"
         Value: "DSTV Media Sales"
       - Key: "Project"
         Value: "DMS Programmatic Trading Portal"
       - Key: "Environment"
         Value: "UAT"
       - Key: "owner"
         Value: "Rani.Bisal"
       - Key: "Team"
         Value: "Business Optimization"
       - Key: "Vendor"
         Value: "Tata Elxsi"
       
      Volumes:
        - Name: ptp-vol


Outputs:
  Service:
    Value: !If [ Fargate, !Ref FargateService, !Ref EC2Service ]